### PR TITLE
Add docker_compose function to tidy up script

### PR DESCRIPTION
**Pull request by damacus**
status command on a serice now returns output rather than taking an
action

### CODE REVIEW

**Comment by carinadigital** [comment]
how did you test this?

**Comment by damacus** [comment]
Note we use a hard coded service name called `service` for the tests. This will be replaced by salt on run. 


```bash
cat test.sh
#/bin/bash

docker_compose() {
	docker-compose -p service -f docker-compose.yml "$1"
}

docker_compose_status() {
  local docker_status=$(docker_compose "ps" | grep "Up" &>/dev/null )$?

  if [[ "$docker_status" == 0 ]];then
    echo "{{service_name}} is running"
  else
    docker_compose "ps"
  fi
}
```

1. docker_compose "help"

Returns docker-compose help

2. `Run PS`

Use a simple docker-compose.yml using pre-built images
```yaml
version: '3'
services:
  redis:
    image: "redis:alpine"
```

```
$ docker-compose up -d
$ docker_compose "ps"
     Name                    Command               State    Ports
-------------------------------------------------------------------
openvpn_redis_1   docker-entrypoint.sh redis ...   Up      6379/tcp
```

3. `docker_compose_status`

Use docker-compose from last test.
```

$ docker-compose -p service up -d
$ docker_compose_status
{{service_name}} is running
$ docker-compose -p service stop
Stopping service_redis_1 ... done
$ docker_compose_status
     Name                    Command               State    Ports
-----------------------------------------------------------------
service_redis_1   docker-entrypoint.sh redis ...   Exit 0

```

**Comment by damacus** [comment]
@carinadigital Changes made, ready to merge.

**Comment by damacus** [comment]
Closing as this is a distraction from ECS.

**Pull request closed without merging**
